### PR TITLE
Fixing state's name by replacing Risal with Rizal

### LINKED ISSUE #4653: Profile: replace Risal, Philippines with Rizal
reported in https://odl.zendesk.com/agent/tickets/57751

### Steps to Reproduce

1. Log in and go to /profile/personal
2. Under "Where are you currently living" set the Country to "Philippines" 
3. Open the drop-down for "State or Territory"

### Expected Behavior

- you can choose the state "Rizal"

### Actual Behavior

- the state is spelled "Risal" 

### Notes

You can confirm this is the correct English spelling for the state in Wikipedia.

We should make this change in [our fork of the iso-3166-2.js library](https://github.com/mitodl/iso-3166-2.js) and then open a pull request upstream.

### PR DESCRIPTION
**Pull request by HamzaIbnFarooq**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/4653

#### What's this PR do?
Fixes typo in a state's name by replacing `Risal` with `Rizal`

#### How to test?
On micromaster do the following steps:
1. Log in and go to /profile/personal
2. Under "Where are you currently living" set the Country to "Philippines" 
3. Open the drop-down for "State or Territory"
4. Search for state "Rizal", you will see "Risal" instead.

Now go to the package.json of micromasters and change `iso-3166-2` dependency's commit id with `hamza/replace-Risal-by-Rizal` (ie: "iso-3166-2": "https://github.com/mitodl/iso-3166-2.js/#hamza/replace-Risal-by-Rizal",)
Now govern the same 4 steps mentioned above, you will see that now "Rizal" is showing up.

OR you can also test it by:
```
iso3166.subdivision("PH", "RIZ")
{
  type: 'Province',
  name: 'Rizal',      # new name
  countryName: 'Philippines',
  countryCode: 'PH',
  code: 'PH-RIZ',
  regionCode: 'RIZ'
}
```

#### Screenshots:
Before:
image
After:
image

### CODE REVIEW

**Review by umarmughal824 — COMMENTED** [review]
Functionality-wise looks good.

**Review by umarmughal824 — APPROVED** [review]
👍

**Comment by umarmughal824** [comment]
@HamzaIbnFarooq make sure to create the micromasters corresponding PR for the updated `iso-3366.js` with your commit version and give the reference of that PR and assign that new PR for review to me.

**Comment by HamzaIbnFarooq** [comment]
> @HamzaIbnFarooq make sure to create the micromasters corresponding PR for the updated `iso-3366.js` with your commit version and give the reference of that PR and assign that new PR for review to me.

Thanks @umarmughal824 for the remainder, will do once this PR gets merged.

**Pull request merged**
